import { DogCard, DogId } from './types';

export const DOG_CATALOG: Record<DogId, DogCard> = {
    miel: {
        id: 'miel',
        name: 'Miel',
        nickname: 'Oficial Médico 🍯',
        cost: 50,
        cooldown: 7.5,
        hp: 300,
        icon: '🍯',
        avatarImg: '/img/pets/Miel.png',
        description: 'Genera platos de Croquetas Doradas periódicamente (+25 🍖) y emite un aura curativa.',
        accentColor: '#ffb595',
        role: 'sun',
    },
    kiaro: {
        id: 'kiaro',
        name: 'Kiaro',
        nickname: 'Guardián Líder 🎾',
        cost: 100,
        cooldown: 7.5,
        hp: 350,
        icon: '🎾',
        avatarImg: '/img/pets/Kiaro.png',
        description: 'Dispara pelotas de tenis veloces. Cada 5 disparos emite un ladrido sónico que empuja a los invasores.',
        accentColor: '#ff7020',
        role: 'shooter',
    },
    nika: {
        id: 'nika',
        name: 'Nika',
        nickname: 'Exploradora Helada ❄️',
        cost: 175,
        cooldown: 7.5,
        hp: 350,
        icon: '❄️',
        avatarImg: '/img/pets/Nika.png',
        description: 'Lanza frisbees y cubos de hielo que ralentizan el avance y velocidad de ataque de los enemigos en un 50%.',
        accentColor: '#00dbe9',
        role: 'ice',
    },
    sam: {
        id: 'sam',
        name: 'Sam',
        nickname: 'Tanque Táctico 🛡️',
        cost: 50,
        cooldown: 25.0,
        hp: 4000,
        icon: '🛡️',
        avatarImg: '/img/pets/Sam.png',
        description: 'Escudo acorazado con 4,000 HP. Bloquea el paso de los monstruos con expresiones tiernas según su daño.',
        accentColor: '#a100f0',
        role: 'wall',
    },
    boneMine: {
        id: 'boneMine',
        name: 'Huesito Mina',
        nickname: 'Trampa Subterránea 🦴',
        cost: 25,
        cooldown: 20.0,
        hp: 150,
        icon: '🦴',
        description: 'Se entierra durante 10s para armarse. Al ser pisada por un monstruo, detona con daño masivo de área (1800 dmg).',
        accentColor: '#fbbf24',
        role: 'mine',
    },
    loveBomb: {
        id: 'loveBomb',
        name: 'Bomba de Amor',
        nickname: 'Estampida Canina 💖',
        cost: 150,
        cooldown: 35.0,
        hp: 100,
        icon: '💖',
        description: 'Explota instantáneamente en un radio de 3x3 casillas con confeti y corazones, desintegrando monstruos (1800 dmg).',
        accentColor: '#f43f5e',
        role: 'bomb',
    },
    boxerDog: {
        id: 'boxerDog',
        name: 'Perrito Bóxer',
        nickname: 'Guardián Melee 🥊',
        cost: 125,
        cooldown: 7.5,
        hp: 450,
        icon: '🥊',
        description: 'Asesta zarpazos y mordiscos rápidos cuerpo a cuerpo a los enemigos a 1 casilla de distancia.',
        accentColor: '#e11d48',
        role: 'melee',
    },
};
